#!/bin/bash

REPOROOT=`git rev-parse --show-toplevel`
COMMIT=`git log --pretty=format:'%H' --reverse | head -1`

if [ -n "$DEBUG" ]; then
    PS4=':${LINENO}+'
    set -x
fi

git commit -m"Commit" $REPOROOT/bin
git rebase -i $COMMIT
